version: '3.9'
#Arrancar docker
services:
  python39:
    build: .
    container_name: python39_container
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env
    tty: true